/**
 * AUTOMATICALLY GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by scripts/syncEnvironment.ts
 * To update with new assets added to public/assets/environment/enviroment_elements, run:
 *   bun run sync:env
 */

export interface EnvironmentElementMeta {
  id: string;
  file: string;
  width: number;
  height: number;
  category: "foliage" | "rock" | "prop" | "structure" | "decoration";
  description: string;
  defaultDepth?: number;
}

export const ENVIRONMENT_ELEMENTS_MAP: Record<string, EnvironmentElementMeta> = {
  enviroment_012: {
    id: "enviroment_012",
    file: "enviroment_012.png",
    width: 162,
    height: 101,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_018: {
    id: "enviroment_018",
    file: "enviroment_018.png",
    width: 135,
    height: 82,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_019: {
    id: "enviroment_019",
    file: "enviroment_019.png",
    width: 129,
    height: 75,
    category: "foliage",
    description: "Vegetación / arbusto de entorno",
    defaultDepth: 1,
  },
  enviroment_020: {
    id: "enviroment_020",
    file: "enviroment_020.png",
    width: 84,
    height: 53,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_021: {
    id: "enviroment_021",
    file: "enviroment_021.png",
    width: 191,
    height: 230,
    category: "structure",
    description: "Estructura / bloque de entorno",
    defaultDepth: -2,
  },
  enviroment_022: {
    id: "enviroment_022",
    file: "enviroment_022.png",
    width: 120,
    height: 210,
    category: "structure",
    description: "Estructura / bloque de entorno",
    defaultDepth: -2,
  },
  enviroment_023: {
    id: "enviroment_023",
    file: "enviroment_023.png",
    width: 135,
    height: 179,
    category: "structure",
    description: "Estructura / bloque de entorno",
    defaultDepth: -2,
  },
  enviroment_024: {
    id: "enviroment_024",
    file: "enviroment_024.png",
    width: 105,
    height: 179,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_025: {
    id: "enviroment_025",
    file: "enviroment_025.png",
    width: 90,
    height: 101,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_026: {
    id: "enviroment_026",
    file: "enviroment_026.png",
    width: 135,
    height: 98,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_027: {
    id: "enviroment_027",
    file: "enviroment_027.png",
    width: 83,
    height: 91,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_028: {
    id: "enviroment_028",
    file: "enviroment_028.png",
    width: 107,
    height: 144,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_029: {
    id: "enviroment_029",
    file: "enviroment_029.png",
    width: 117,
    height: 85,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_030: {
    id: "enviroment_030",
    file: "enviroment_030.png",
    width: 84,
    height: 86,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_031: {
    id: "enviroment_031",
    file: "enviroment_031.png",
    width: 66,
    height: 83,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_032: {
    id: "enviroment_032",
    file: "enviroment_032.png",
    width: 61,
    height: 82,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_033: {
    id: "enviroment_033",
    file: "enviroment_033.png",
    width: 90,
    height: 70,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_034: {
    id: "enviroment_034",
    file: "enviroment_034.png",
    width: 115,
    height: 122,
    category: "structure",
    description: "Estructura / bloque de entorno",
    defaultDepth: -2,
  },
  enviroment_035: {
    id: "enviroment_035",
    file: "enviroment_035.png",
    width: 131,
    height: 122,
    category: "structure",
    description: "Estructura / bloque de entorno",
    defaultDepth: -2,
  },
  enviroment_036: {
    id: "enviroment_036",
    file: "enviroment_036.png",
    width: 113,
    height: 120,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_037: {
    id: "enviroment_037",
    file: "enviroment_037.png",
    width: 157,
    height: 86,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_038: {
    id: "enviroment_038",
    file: "enviroment_038.png",
    width: 199,
    height: 83,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_040: {
    id: "enviroment_040",
    file: "enviroment_040.png",
    width: 298,
    height: 85,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_041: {
    id: "enviroment_041",
    file: "enviroment_041.png",
    width: 103,
    height: 83,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_042: {
    id: "enviroment_042",
    file: "enviroment_042.png",
    width: 139,
    height: 81,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_049: {
    id: "enviroment_049",
    file: "enviroment_049.png",
    width: 95,
    height: 96,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_056: {
    id: "enviroment_056",
    file: "enviroment_056.png",
    width: 124,
    height: 94,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_059: {
    id: "enviroment_059",
    file: "enviroment_059.png",
    width: 136,
    height: 82,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_060: {
    id: "enviroment_060",
    file: "enviroment_060.png",
    width: 110,
    height: 82,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
  enviroment_062: {
    id: "enviroment_062",
    file: "enviroment_062.png",
    width: 95,
    height: 70,
    category: "prop",
    description: "Elemento de escenografía de entorno",
    defaultDepth: 1,
  },
};

export const ENVIRONMENT_ELEMENTS_LIST = Object.values(ENVIRONMENT_ELEMENTS_MAP);

export type EnvironmentElementId = keyof typeof ENVIRONMENT_ELEMENTS_MAP;

/**
 * Obtiene la metadata de un elemento de entorno con fallback seguro.
 * Si el elemento no existe en el mapa (por ser recién añadido), se genera una definición por defecto.
 */
export function getEnvironmentElementMeta(id: string): EnvironmentElementMeta {
  if (ENVIRONMENT_ELEMENTS_MAP[id]) {
    return ENVIRONMENT_ELEMENTS_MAP[id];
  }
  const cleanId = id.replace(/\.[^/.]+$/, "");
  if (ENVIRONMENT_ELEMENTS_MAP[cleanId]) {
    return ENVIRONMENT_ELEMENTS_MAP[cleanId];
  }
  return {
    id: cleanId,
    file: id.endsWith(".png") ? id : `${id}.png`,
    width: 128,
    height: 128,
    category: "prop",
    description: "Elemento de entorno dinámico",
    defaultDepth: 0,
  };
}

/**
 * Presets semánticos para facilitar la selección de elementos de entorno
 */
export const ENVIRONMENT_PRESETS = {
  STRUCTURE_TALL_1: "enviroment_021" as EnvironmentElementId,
  STRUCTURE_TALL_2: "enviroment_022" as EnvironmentElementId,
  STRUCTURE_TALL_3: "enviroment_023" as EnvironmentElementId,
  BLOCK_MEDIUM_1: "enviroment_012" as EnvironmentElementId,
  BLOCK_MEDIUM_2: "enviroment_021" as EnvironmentElementId,
  FOLIAGE_BUSH_1: "enviroment_019" as EnvironmentElementId,
  FOLIAGE_BUSH_2: "enviroment_062" as EnvironmentElementId,
  SCENERY_ROCK_1: "enviroment_012" as EnvironmentElementId,
  SCENERY_ROCK_2: "enviroment_018" as EnvironmentElementId,
  SCENERY_ROCK_3: "enviroment_020" as EnvironmentElementId,
} as const;
