export interface GroundElementMeta {
  id: string;
  file: string;
  width: number;
  height: number;
  category: "island" | "tile" | "chunk" | "column";
  description: string;
  hitbox: {
    width: number;
    height: number;
    offsetX: number;
    offsetY: number;
  };
}

export const GROUND_ELEMENTS_MAP: Record<string, GroundElementMeta> = {
  ground_000: {
    id: "ground_000",
    file: "ground_000.png",
    width: 134,
    height: 159,
    category: "column",
    description: "Columna / pilar vertical de tierra",
    hitbox: { width: 113, height: 135, offsetX: 10, offsetY: 15 },
  },
  ground_004: {
    id: "ground_004",
    file: "ground_004.png",
    width: 121,
    height: 155,
    category: "column",
    description: "Columna / pilar vertical de tierra",
    hitbox: { width: 102, height: 131, offsetX: 9, offsetY: 15 },
  },
  ground_005: {
    id: "ground_005",
    file: "ground_005.png",
    width: 140,
    height: 154,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 123, height: 107, offsetX: 8, offsetY: 23 },
  },
  ground_006: {
    id: "ground_006",
    file: "ground_006.png",
    width: 137,
    height: 153,
    category: "column",
    description: "Columna / pilar vertical de tierra",
    hitbox: { width: 116, height: 130, offsetX: 10, offsetY: 15 },
  },
  ground_010: {
    id: "ground_010",
    file: "ground_010.png",
    width: 138,
    height: 126,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 121, height: 88, offsetX: 8, offsetY: 18 },
  },
  ground_011: {
    id: "ground_011",
    file: "ground_011.png",
    width: 123,
    height: 126,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 108, height: 88, offsetX: 7, offsetY: 18 },
  },
  ground_013: {
    id: "ground_013",
    file: "ground_013.png",
    width: 159,
    height: 126,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 139, height: 88, offsetX: 10, offsetY: 18 },
  },
  ground_016: {
    id: "ground_016",
    file: "ground_016.png",
    width: 129,
    height: 126,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 113, height: 88, offsetX: 8, offsetY: 18 },
  },
  ground_017: {
    id: "ground_017",
    file: "ground_017.png",
    width: 128,
    height: 126,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 112, height: 88, offsetX: 8, offsetY: 18 },
  },
  ground_018: {
    id: "ground_018",
    file: "ground_018.png",
    width: 126,
    height: 126,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 110, height: 88, offsetX: 8, offsetY: 18 },
  },
  ground_019: {
    id: "ground_019",
    file: "ground_019.png",
    width: 171,
    height: 125,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 150, height: 87, offsetX: 10, offsetY: 18 },
  },
  ground_020: {
    id: "ground_020",
    file: "ground_020.png",
    width: 164,
    height: 125,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 144, height: 87, offsetX: 10, offsetY: 18 },
  },
  ground_021: {
    id: "ground_021",
    file: "ground_021.png",
    width: 127,
    height: 141,
    category: "column",
    description: "Columna / pilar vertical de tierra",
    hitbox: { width: 107, height: 119, offsetX: 10, offsetY: 14 },
  },
  ground_022: {
    id: "ground_022",
    file: "ground_022.png",
    width: 133,
    height: 140,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 117, height: 98, offsetX: 8, offsetY: 21 },
  },
  ground_023: {
    id: "ground_023",
    file: "ground_023.png",
    width: 134,
    height: 140,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 117, height: 98, offsetX: 8, offsetY: 21 },
  },
  ground_024: {
    id: "ground_024",
    file: "ground_024.png",
    width: 166,
    height: 138,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 146, height: 96, offsetX: 10, offsetY: 20 },
  },
  ground_025: {
    id: "ground_025",
    file: "ground_025.png",
    width: 140,
    height: 139,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 123, height: 97, offsetX: 8, offsetY: 20 },
  },
  ground_026: {
    id: "ground_026",
    file: "ground_026.png",
    width: 138,
    height: 139,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 121, height: 97, offsetX: 8, offsetY: 20 },
  },
  ground_027: {
    id: "ground_027",
    file: "ground_027.png",
    width: 125,
    height: 139,
    category: "column",
    description: "Columna / pilar vertical de tierra",
    hitbox: { width: 106, height: 118, offsetX: 9, offsetY: 13 },
  },
  ground_028: {
    id: "ground_028",
    file: "ground_028.png",
    width: 106,
    height: 134,
    category: "column",
    description: "Columna / pilar vertical de tierra",
    hitbox: { width: 90, height: 113, offsetX: 8, offsetY: 13 },
  },
  ground_029: {
    id: "ground_029",
    file: "ground_029.png",
    width: 83,
    height: 125,
    category: "column",
    description: "Columna / pilar vertical de tierra",
    hitbox: { width: 70, height: 106, offsetX: 6, offsetY: 12 },
  },
  ground_030: {
    id: "ground_030",
    file: "ground_030.png",
    width: 99,
    height: 122,
    category: "column",
    description: "Columna / pilar vertical de tierra",
    hitbox: { width: 84, height: 103, offsetX: 7, offsetY: 12 },
  },
  ground_031: {
    id: "ground_031",
    file: "ground_031.png",
    width: 186,
    height: 143,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 163, height: 100, offsetX: 11, offsetY: 21 },
  },
  ground_032: {
    id: "ground_032",
    file: "ground_032.png",
    width: 173,
    height: 140,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 152, height: 98, offsetX: 10, offsetY: 21 },
  },
  ground_033: {
    id: "ground_033",
    file: "ground_033.png",
    width: 184,
    height: 133,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 161, height: 93, offsetX: 11, offsetY: 19 },
  },
  ground_034: {
    id: "ground_034",
    file: "ground_034.png",
    width: 165,
    height: 123,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 145, height: 86, offsetX: 10, offsetY: 18 },
  },
  ground_035: {
    id: "ground_035",
    file: "ground_035.png",
    width: 161,
    height: 121,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 141, height: 84, offsetX: 10, offsetY: 18 },
  },
  ground_036: {
    id: "ground_036",
    file: "ground_036.png",
    width: 143,
    height: 122,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 125, height: 85, offsetX: 9, offsetY: 18 },
  },
  ground_037: {
    id: "ground_037",
    file: "ground_037.png",
    width: 165,
    height: 123,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 145, height: 86, offsetX: 10, offsetY: 18 },
  },
  ground_038: {
    id: "ground_038",
    file: "ground_038.png",
    width: 194,
    height: 122,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 170, height: 85, offsetX: 12, offsetY: 18 },
  },
  ground_039: {
    id: "ground_039",
    file: "ground_039.png",
    width: 130,
    height: 95,
    category: "island",
    description: "Isla flotante / plataforma de césped",
    hitbox: { width: 117, height: 30, offsetX: 6, offsetY: 55 },
  },
  ground_040: {
    id: "ground_040",
    file: "ground_040.png",
    width: 210,
    height: 93,
    category: "tile",
    description: "Bloque de suelo horizontal",
    hitbox: { width: 193, height: 30, offsetX: 8, offsetY: 50 },
  },
  ground_041: {
    id: "ground_041",
    file: "ground_041.png",
    width: 95,
    height: 90,
    category: "island",
    description: "Isla flotante / plataforma de césped",
    hitbox: { width: 85, height: 30, offsetX: 5, offsetY: 40 },
  },
  ground_042: {
    id: "ground_042",
    file: "ground_042.png",
    width: 118,
    height: 90,
    category: "island",
    description: "Isla flotante / plataforma de césped",
    hitbox: { width: 106, height: 30, offsetX: 6, offsetY: 40 },
  },
  ground_043: {
    id: "ground_043",
    file: "ground_043.png",
    width: 183,
    height: 88,
    category: "island",
    description: "Isla flotante / plataforma de césped",
    hitbox: { width: 164, height: 30, offsetX: 9, offsetY: 45 },
  },
  ground_044: {
    id: "ground_044",
    file: "ground_044.png",
    width: 153,
    height: 87,
    category: "island",
    description: "Isla flotante con flor (rich_platform)",
    hitbox: { width: 140, height: 30, offsetX: 6, offsetY: 45 },
  },
  ground_045: {
    id: "ground_045",
    file: "ground_045.png",
    width: 187,
    height: 87,
    category: "island",
    description: "Isla flotante / plataforma de césped",
    hitbox: { width: 168, height: 30, offsetX: 9, offsetY: 45 },
  },
  ground_046: {
    id: "ground_046",
    file: "ground_046.png",
    width: 131,
    height: 86,
    category: "island",
    description: "Isla flotante / plataforma de césped",
    hitbox: { width: 117, height: 30, offsetX: 7, offsetY: 45 },
  },
  ground_047: {
    id: "ground_047",
    file: "ground_047.png",
    width: 212,
    height: 83,
    category: "tile",
    description: "Bloque de suelo horizontal",
    hitbox: { width: 195, height: 23, offsetX: 8, offsetY: 45 },
  },
  ground_048: {
    id: "ground_048",
    file: "ground_048.png",
    width: 79,
    height: 102,
    category: "column",
    description: "Columna / pilar vertical de tierra",
    hitbox: { width: 67, height: 86, offsetX: 6, offsetY: 10 },
  },
  ground_049: {
    id: "ground_049",
    file: "ground_049.png",
    width: 143,
    height: 115,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 125, height: 80, offsetX: 9, offsetY: 17 },
  },
  ground_050: {
    id: "ground_050",
    file: "ground_050.png",
    width: 123,
    height: 117,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 108, height: 81, offsetX: 7, offsetY: 17 },
  },
  ground_051: {
    id: "ground_051",
    file: "ground_051.png",
    width: 117,
    height: 120,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 102, height: 84, offsetX: 7, offsetY: 18 },
  },
  ground_052: {
    id: "ground_052",
    file: "ground_052.png",
    width: 114,
    height: 122,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 100, height: 85, offsetX: 7, offsetY: 18 },
  },
  ground_053: {
    id: "ground_053",
    file: "ground_053.png",
    width: 112,
    height: 121,
    category: "chunk",
    description: "Bloque de tierra y roca",
    hitbox: { width: 98, height: 84, offsetX: 7, offsetY: 18 },
  },
  ground_054: {
    id: "ground_054",
    file: "ground_054.png",
    width: 100,
    height: 121,
    category: "column",
    description: "Columna / pilar vertical de tierra",
    hitbox: { width: 85, height: 102, offsetX: 7, offsetY: 12 },
  },
  ground_055: {
    id: "ground_055",
    file: "ground_055.png",
    width: 98,
    height: 121,
    category: "column",
    description: "Columna / pilar vertical de tierra",
    hitbox: { width: 83, height: 102, offsetX: 7, offsetY: 12 },
  },
  ground_056: {
    id: "ground_056",
    file: "ground_056.png",
    width: 93,
    height: 122,
    category: "column",
    description: "Columna / pilar vertical de tierra",
    hitbox: { width: 79, height: 103, offsetX: 7, offsetY: 12 },
  },
  ground_057: {
    id: "ground_057",
    file: "ground_057.png",
    width: 101,
    height: 122,
    category: "column",
    description: "Columna / pilar vertical de tierra",
    hitbox: { width: 85, height: 103, offsetX: 8, offsetY: 12 },
  },
  ground_058: {
    id: "ground_058",
    file: "ground_058.png",
    width: 63,
    height: 85,
    category: "column",
    description: "Columna / pilar vertical de tierra",
    hitbox: { width: 53, height: 72, offsetX: 5, offsetY: 8 },
  },
  ground_099: {
    id: "ground_099",
    file: "ground_099.png",
    width: 240,
    height: 124,
    category: "tile",
    description: "Bloque de suelo horizontal",
    hitbox: { width: 220, height: 60, offsetX: 10, offsetY: 60 },
  },
  ground_100: {
    id: "ground_100",
    file: "ground_100.png",
    width: 240,
    height: 111,
    category: "tile",
    description: "Bloque de suelo horizontal",
    hitbox: { width: 220, height: 72, offsetX: 10, offsetY: 40 },
  },
  ground_101: {
    id: "ground_101",
    file: "ground_101.png",
    width: 247,
    height: 111,
    category: "tile",
    description: "Bloque de suelo horizontal",
    hitbox: { width: 227, height: 72, offsetX: 10, offsetY: 45 },
  },
  ground_102: {
    id: "ground_102",
    file: "ground_102.png",
    width: 234,
    height: 110,
    category: "tile",
    description: "Bloque de suelo horizontal",
    hitbox: { width: 215, height: 71, offsetX: 9, offsetY: 40 },
  },
  ground_103: {
    id: "ground_103",
    file: "ground_103.png",
    width: 244,
    height: 103,
    category: "tile",
    description: "Bloque de suelo horizontal",
    hitbox: { width: 224, height: 71, offsetX: 10, offsetY: 40 },
  },
  ground_104: {
    id: "ground_104",
    file: "ground_104.png",
    width: 245,
    height: 95,
    category: "tile",
    description: "Bloque de suelo estándar (ground_tile)",
    hitbox: { width: 225, height: 65, offsetX: 10, offsetY: 20 },
  },
};

export const GROUND_ELEMENTS_LIST = Object.values(GROUND_ELEMENTS_MAP);

export type GroundElementId = keyof typeof GROUND_ELEMENTS_MAP;

/**
 * Presets semánticos para facilitar la elección de piezas comunes
 */
export const GROUND_PRESETS = {
  // Islas flotantes (plataformas de salto)
  ISLAND_FLOWER: "ground_044" as GroundElementId, // Con flor y hojas (la clásica)
  ISLAND_WIDE: "ground_047" as GroundElementId, // Muy ancha (212px)
  ISLAND_LARGE: "ground_045" as GroundElementId, // Grande (187px)
  ISLAND_MEDIUM: "ground_043" as GroundElementId, // Mediana (183px)
  ISLAND_SMALL: "ground_046" as GroundElementId, // Pequeña (131px)
  ISLAND_ROUNDED: "ground_039" as GroundElementId, // Redondeada (130px)
  ISLAND_COMPACT: "ground_042" as GroundElementId, // Compacta (118px)
  ISLAND_MINI: "ground_041" as GroundElementId, // Mini (95px)

  // Bloques de suelo horizontal
  GROUND_DEFAULT: "ground_104" as GroundElementId, // 245x95 clásico
  GROUND_LUSH_1: "ground_099" as GroundElementId, // 240x124
  GROUND_LUSH_2: "ground_100" as GroundElementId, // 240x111
  GROUND_LUSH_3: "ground_101" as GroundElementId, // 247x111
  GROUND_LUSH_4: "ground_102" as GroundElementId, // 234x110
  GROUND_LUSH_5: "ground_103" as GroundElementId, // 244x103
  GROUND_WIDE_TILE: "ground_040" as GroundElementId, // 210x93

  // Columnas verticales de tierra / acantilados
  COLUMN_TALL_1: "ground_000" as GroundElementId,
  COLUMN_TALL_2: "ground_004" as GroundElementId,
  COLUMN_TALL_3: "ground_006" as GroundElementId,
  COLUMN_MEDIUM_1: "ground_021" as GroundElementId,
  COLUMN_MEDIUM_2: "ground_027" as GroundElementId,
  COLUMN_SLIM_1: "ground_029" as GroundElementId,
  COLUMN_SLIM_2: "ground_030" as GroundElementId,
  COLUMN_SHORT: "ground_048" as GroundElementId,
} as const;
