import fs from "fs";
import path from "path";
import sharp from "sharp";

const ENV_FOLDER = path.resolve("public/assets/environment/enviroment_elements");
const OUTPUT_FILE = path.resolve("src/game/config/environmentElements.ts");

async function syncEnvironment() {
  if (!fs.existsSync(ENV_FOLDER)) {
    console.error(`Folder not found: ${ENV_FOLDER}`);
    process.exit(1);
  }

  const files = fs
    .readdirSync(ENV_FOLDER)
    .filter((f) => /\.(png|jpe?g|webp)$/i.test(f))
    .sort();

  console.log(`Found ${files.length} environment element images in ${ENV_FOLDER}`);

  const elements: Array<{
    id: string;
    file: string;
    width: number;
    height: number;
    category: "foliage" | "rock" | "prop" | "structure" | "decoration";
    description: string;
    defaultDepth: number;
  }> = [];

  for (const file of files) {
    const filePath = path.join(ENV_FOLDER, file);
    const metadata = await sharp(filePath).metadata();
    const width = metadata.width || 100;
    const height = metadata.height || 100;
    const baseId = path.parse(file).name;

    let category: "foliage" | "rock" | "prop" | "structure" | "decoration" = "prop";
    let description = "Elemento de escenografía de entorno";
    let defaultDepth = 1;

    if (height > 130 && width < 80) {
      category = "structure";
      description = "Pilar / poste decorativo de entorno";
      defaultDepth = 0;
    } else if (height > 120 && width > 110) {
      category = "structure";
      description = "Estructura / bloque de entorno";
      defaultDepth = -2;
    } else if (width > 120 && height < 80) {
      category = "foliage";
      description = "Vegetación / arbusto de entorno";
      defaultDepth = 1;
    } else if (width < 60 && height < 60) {
      category = "decoration";
      description = "Detalle decorativo de entorno";
      defaultDepth = 2;
    } else {
      category = "prop";
      description = "Elemento de escenografía de entorno";
      defaultDepth = 1;
    }

    elements.push({
      id: baseId,
      file,
      width,
      height,
      category,
      description,
      defaultDepth,
    });
  }

  const codeLines: string[] = [
    `/**`,
    ` * AUTOMATICALLY GENERATED FILE - DO NOT EDIT MANUALLY`,
    ` * Generated by scripts/syncEnvironment.ts`,
    ` * To update with new assets added to public/assets/environment/enviroment_elements, run:`,
    ` *   bun run sync:env`,
    ` */`,
    ``,
    `export interface EnvironmentElementMeta {`,
    `  id: string;`,
    `  file: string;`,
    `  width: number;`,
    `  height: number;`,
    `  category: "foliage" | "rock" | "prop" | "structure" | "decoration";`,
    `  description: string;`,
    `  defaultDepth?: number;`,
    `}`,
    ``,
    `export const ENVIRONMENT_ELEMENTS_MAP: Record<string, EnvironmentElementMeta> = {`,
  ];

  for (const el of elements) {
    codeLines.push(`  ${el.id}: {`);
    codeLines.push(`    id: "${el.id}",`);
    codeLines.push(`    file: "${el.file}",`);
    codeLines.push(`    width: ${el.width},`);
    codeLines.push(`    height: ${el.height},`);
    codeLines.push(`    category: "${el.category}",`);
    codeLines.push(`    description: "${el.description}",`);
    codeLines.push(`    defaultDepth: ${el.defaultDepth},`);
    codeLines.push(`  },`);
  }

  codeLines.push(`};`);
  codeLines.push(``);
  codeLines.push(`export const ENVIRONMENT_ELEMENTS_LIST = Object.values(ENVIRONMENT_ELEMENTS_MAP);`);
  codeLines.push(``);
  codeLines.push(`export type EnvironmentElementId = keyof typeof ENVIRONMENT_ELEMENTS_MAP;`);
  codeLines.push(``);
  codeLines.push(`/**`);
  codeLines.push(` * Obtiene la metadata de un elemento de entorno con fallback seguro.`);
  codeLines.push(` * Si el elemento no existe en el mapa (por ser recién añadido), se genera una definición por defecto.`);
  codeLines.push(` */`);
  codeLines.push(`export function getEnvironmentElementMeta(id: string): EnvironmentElementMeta {`);
  codeLines.push(`  if (ENVIRONMENT_ELEMENTS_MAP[id]) {`);
  codeLines.push(`    return ENVIRONMENT_ELEMENTS_MAP[id];`);
  codeLines.push(`  }`);
  codeLines.push(`  const cleanId = id.replace(/\\.[^/.]+$/, "");`);
  codeLines.push(`  if (ENVIRONMENT_ELEMENTS_MAP[cleanId]) {`);
  codeLines.push(`    return ENVIRONMENT_ELEMENTS_MAP[cleanId];`);
  codeLines.push(`  }`);
  codeLines.push(`  return {`);
  codeLines.push(`    id: cleanId,`);
  codeLines.push(`    file: id.endsWith(".png") ? id : \`\${id}.png\`,`);
  codeLines.push(`    width: 128,`);
  codeLines.push(`    height: 128,`);
  codeLines.push(`    category: "prop",`);
  codeLines.push(`    description: "Elemento de entorno dinámico",`);
  codeLines.push(`    defaultDepth: 0,`);
  codeLines.push(`  };`);
  codeLines.push(`}`);
  codeLines.push(``);
  const tall = elements.filter((e) => e.height >= 150);
  const blocks = elements.filter((e) => e.category === "structure" || (e.height >= 90 && e.height < 150));
  const foliage = elements.filter((e) => e.category === "foliage" || (e.width > 90 && e.height < 80));
  const rocks = elements.filter((e) => e.category === "prop");

  codeLines.push(`/**`);
  codeLines.push(` * Presets semánticos para facilitar la selección de elementos de entorno`);
  codeLines.push(` */`);
  codeLines.push(`export const ENVIRONMENT_PRESETS = {`);
  if (tall[0]) codeLines.push(`  STRUCTURE_TALL_1: "${tall[0].id}" as EnvironmentElementId,`);
  if (tall[1]) codeLines.push(`  STRUCTURE_TALL_2: "${tall[1].id}" as EnvironmentElementId,`);
  if (tall[2]) codeLines.push(`  STRUCTURE_TALL_3: "${tall[2].id}" as EnvironmentElementId,`);
  if (blocks[0]) codeLines.push(`  BLOCK_MEDIUM_1: "${blocks[0].id}" as EnvironmentElementId,`);
  if (blocks[1]) codeLines.push(`  BLOCK_MEDIUM_2: "${blocks[1].id}" as EnvironmentElementId,`);
  if (foliage[0]) codeLines.push(`  FOLIAGE_BUSH_1: "${foliage[0].id}" as EnvironmentElementId,`);
  if (foliage[1]) codeLines.push(`  FOLIAGE_BUSH_2: "${foliage[1].id}" as EnvironmentElementId,`);
  if (rocks[0]) codeLines.push(`  SCENERY_ROCK_1: "${rocks[0].id}" as EnvironmentElementId,`);
  if (rocks[1]) codeLines.push(`  SCENERY_ROCK_2: "${rocks[1].id}" as EnvironmentElementId,`);
  if (rocks[2]) codeLines.push(`  SCENERY_ROCK_3: "${rocks[2].id}" as EnvironmentElementId,`);
  codeLines.push(`} as const;`);
  codeLines.push(``);

  fs.writeFileSync(OUTPUT_FILE, codeLines.join("\n"), "utf-8");
  console.log(`Successfully generated ${OUTPUT_FILE} with ${elements.length} elements!`);
}

syncEnvironment().catch(console.error);
